# Utilizamos la imagen Alpine más ligera de Node
FROM node:18.17.0-alpine

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos primero solo el archivo de dependencias para aprovechar la caché de Docker
COPY package.json package-lock.json ./

# Instalamos las dependencias
RUN npm install --silent

# Copiamos todos los archivos de la aplicación al contenedor
COPY . .

# Exponemos el puerto 4200 para el servidor de desarrollo
EXPOSE 3000

# Ejecutamos el servidor de desarrollo al iniciar el contenedor
CMD ["npm", "run", "start"]